/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifndef __NETWORKCONFIG1_AUTOGEN_H__
#define __NETWORKCONFIG1_AUTOGEN_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.lgi.rdk.utils.networkconfig1 */

#define TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1 (com_lgi_rdk_utils_networkconfig1_get_type ())
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1, ComLgiRdkUtilsNetworkconfig1))
#define IS_COM_LGI_RDK_UTILS_NETWORKCONFIG1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1))
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1, ComLgiRdkUtilsNetworkconfig1Iface))

struct _ComLgiRdkUtilsNetworkconfig1;
typedef struct _ComLgiRdkUtilsNetworkconfig1 ComLgiRdkUtilsNetworkconfig1;
typedef struct _ComLgiRdkUtilsNetworkconfig1Iface ComLgiRdkUtilsNetworkconfig1Iface;

struct _ComLgiRdkUtilsNetworkconfig1Iface
{
  GTypeInterface parent_iface;


  gboolean (*handle_dhcprenew) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_enable) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id,
    gboolean arg_enable);

  gboolean (*handle_get_active_interface) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_interfaces) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_param) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id,
    const gchar *arg_paramName);

  gboolean (*handle_get_params) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id);

  gboolean (*handle_get_status) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id);

  gboolean (*handle_is_enabled) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id);

  gboolean (*handle_reset_configuration) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_send_wake_up_request) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_mac);

  gboolean (*handle_set_active_interface) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id);

  gboolean (*handle_set_param) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_id,
    const gchar *arg_paramName,
    const gchar *arg_paramValue);

  void (*ipv4_configuration_changed) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id);

  void (*ipv6_configuration_changed) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id);

  void (*network_configuration_service_started) (
    ComLgiRdkUtilsNetworkconfig1 *object);

  void (*networking_event) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id,
    const gchar *arg_event,
    guint arg_count,
    GVariant *arg_params);

  void (*status_changed) (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id,
    const gchar *arg_ifaceStatus);

};

GType com_lgi_rdk_utils_networkconfig1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *com_lgi_rdk_utils_networkconfig1_interface_info (void);
guint com_lgi_rdk_utils_networkconfig1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void com_lgi_rdk_utils_networkconfig1_complete_get_interfaces (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    guint count,
    const gchar *const *ids);

void com_lgi_rdk_utils_networkconfig1_complete_enable (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status);

void com_lgi_rdk_utils_networkconfig1_complete_is_enabled (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status,
    gboolean enabled);

void com_lgi_rdk_utils_networkconfig1_complete_get_active_interface (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *id,
    gint status);

void com_lgi_rdk_utils_networkconfig1_complete_set_active_interface (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status);

void com_lgi_rdk_utils_networkconfig1_complete_get_params (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status,
    guint count,
    GVariant *params);

void com_lgi_rdk_utils_networkconfig1_complete_get_param (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status,
    const gchar *paramValue);

void com_lgi_rdk_utils_networkconfig1_complete_set_param (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status);

void com_lgi_rdk_utils_networkconfig1_complete_dhcprenew (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status);

void com_lgi_rdk_utils_networkconfig1_complete_get_status (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status,
    const gchar *ifaceStatus);

void com_lgi_rdk_utils_networkconfig1_complete_reset_configuration (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status);

void com_lgi_rdk_utils_networkconfig1_complete_send_wake_up_request (
    ComLgiRdkUtilsNetworkconfig1 *object,
    GDBusMethodInvocation *invocation,
    gint status);



/* D-Bus signal emissions functions: */
void com_lgi_rdk_utils_networkconfig1_emit_network_configuration_service_started (
    ComLgiRdkUtilsNetworkconfig1 *object);

void com_lgi_rdk_utils_networkconfig1_emit_ipv4_configuration_changed (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id);

void com_lgi_rdk_utils_networkconfig1_emit_ipv6_configuration_changed (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id);

void com_lgi_rdk_utils_networkconfig1_emit_status_changed (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id,
    const gchar *arg_ifaceStatus);

void com_lgi_rdk_utils_networkconfig1_emit_networking_event (
    ComLgiRdkUtilsNetworkconfig1 *object,
    const gchar *arg_id,
    const gchar *arg_event,
    guint arg_count,
    GVariant *arg_params);



/* D-Bus method calls: */
void com_lgi_rdk_utils_networkconfig1_call_get_interfaces (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_interfaces_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    guint *out_count,
    gchar ***out_ids,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_interfaces_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    guint *out_count,
    gchar ***out_ids,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_enable (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    gboolean arg_enable,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_enable_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_enable_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    gboolean arg_enable,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_is_enabled (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_is_enabled_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    gboolean *out_enabled,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_is_enabled_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    gint *out_status,
    gboolean *out_enabled,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_get_active_interface (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_active_interface_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gchar **out_id,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_active_interface_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gchar **out_id,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_set_active_interface (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_set_active_interface_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_set_active_interface_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_get_params (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_params_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    guint *out_count,
    GVariant **out_params,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_params_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    gint *out_status,
    guint *out_count,
    GVariant **out_params,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_get_param (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    const gchar *arg_paramName,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_param_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    gchar **out_paramValue,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_param_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    const gchar *arg_paramName,
    gint *out_status,
    gchar **out_paramValue,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_set_param (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    const gchar *arg_paramName,
    const gchar *arg_paramValue,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_set_param_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_set_param_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    const gchar *arg_paramName,
    const gchar *arg_paramValue,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_dhcprenew (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_dhcprenew_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_dhcprenew_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_get_status (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_status_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    gchar **out_ifaceStatus,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_get_status_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_id,
    gint *out_status,
    gchar **out_ifaceStatus,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_reset_configuration (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_reset_configuration_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_reset_configuration_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);

void com_lgi_rdk_utils_networkconfig1_call_send_wake_up_request (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_mac,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean com_lgi_rdk_utils_networkconfig1_call_send_wake_up_request_finish (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error);

gboolean com_lgi_rdk_utils_networkconfig1_call_send_wake_up_request_sync (
    ComLgiRdkUtilsNetworkconfig1 *proxy,
    const gchar *arg_mac,
    gint *out_status,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY (com_lgi_rdk_utils_networkconfig1_proxy_get_type ())
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY, ComLgiRdkUtilsNetworkconfig1Proxy))
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY, ComLgiRdkUtilsNetworkconfig1ProxyClass))
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY, ComLgiRdkUtilsNetworkconfig1ProxyClass))
#define IS_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY))
#define IS_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_PROXY))

typedef struct _ComLgiRdkUtilsNetworkconfig1Proxy ComLgiRdkUtilsNetworkconfig1Proxy;
typedef struct _ComLgiRdkUtilsNetworkconfig1ProxyClass ComLgiRdkUtilsNetworkconfig1ProxyClass;
typedef struct _ComLgiRdkUtilsNetworkconfig1ProxyPrivate ComLgiRdkUtilsNetworkconfig1ProxyPrivate;

struct _ComLgiRdkUtilsNetworkconfig1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  ComLgiRdkUtilsNetworkconfig1ProxyPrivate *priv;
};

struct _ComLgiRdkUtilsNetworkconfig1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType com_lgi_rdk_utils_networkconfig1_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComLgiRdkUtilsNetworkconfig1Proxy, g_object_unref)
#endif

void com_lgi_rdk_utils_networkconfig1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComLgiRdkUtilsNetworkconfig1 *com_lgi_rdk_utils_networkconfig1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
ComLgiRdkUtilsNetworkconfig1 *com_lgi_rdk_utils_networkconfig1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void com_lgi_rdk_utils_networkconfig1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
ComLgiRdkUtilsNetworkconfig1 *com_lgi_rdk_utils_networkconfig1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
ComLgiRdkUtilsNetworkconfig1 *com_lgi_rdk_utils_networkconfig1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON (com_lgi_rdk_utils_networkconfig1_skeleton_get_type ())
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON, ComLgiRdkUtilsNetworkconfig1Skeleton))
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON, ComLgiRdkUtilsNetworkconfig1SkeletonClass))
#define COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON, ComLgiRdkUtilsNetworkconfig1SkeletonClass))
#define IS_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON))
#define IS_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_COM_LGI_RDK_UTILS_NETWORKCONFIG1_SKELETON))

typedef struct _ComLgiRdkUtilsNetworkconfig1Skeleton ComLgiRdkUtilsNetworkconfig1Skeleton;
typedef struct _ComLgiRdkUtilsNetworkconfig1SkeletonClass ComLgiRdkUtilsNetworkconfig1SkeletonClass;
typedef struct _ComLgiRdkUtilsNetworkconfig1SkeletonPrivate ComLgiRdkUtilsNetworkconfig1SkeletonPrivate;

struct _ComLgiRdkUtilsNetworkconfig1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  ComLgiRdkUtilsNetworkconfig1SkeletonPrivate *priv;
};

struct _ComLgiRdkUtilsNetworkconfig1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType com_lgi_rdk_utils_networkconfig1_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ComLgiRdkUtilsNetworkconfig1Skeleton, g_object_unref)
#endif

ComLgiRdkUtilsNetworkconfig1 *com_lgi_rdk_utils_networkconfig1_skeleton_new (void);


G_END_DECLS

#endif /* __NETWORKCONFIG1_AUTOGEN_H__ */
