/*
 * Generated by gdbus-codegen 2.56.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "wifimanagement1.autogen.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.lgi.rdk.utils.wifimanagement1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:ComLgiRdkUtilsWifimanagement1
 * @title: ComLgiRdkUtilsWifimanagement1
 * @short_description: Generated C code for the com.lgi.rdk.utils.wifimanagement1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.lgi.rdk.utils.wifimanagement1 ---- */

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_IN_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_count =
{
  {
    -1,
    (gchar *) "count",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_netids =
{
  {
    -1,
    (gchar *) "netids",
    (gchar *) "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_basic_params =
{
  {
    -1,
    (gchar *) "basic_params",
    (gchar *) "aa{ss}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_status,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_count,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_netids,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_basic_params,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids =
{
  {
    -1,
    (gchar *) "GetSSIDs",
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids_OUT_ARG_pointers,
    NULL
  },
  "handle-get-ssids",
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_IN_ARG_netid =
{
  {
    -1,
    (gchar *) "netid",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_IN_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_IN_ARG_id,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_IN_ARG_netid,
  NULL
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_count =
{
  {
    -1,
    (gchar *) "count",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_params =
{
  {
    -1,
    (gchar *) "params",
    (gchar *) "a{ss}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_status,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_count,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_params,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams =
{
  {
    -1,
    (gchar *) "GetSSIDParams",
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams_OUT_ARG_pointers,
    NULL
  },
  "handle-get-ssidparams",
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_netid =
{
  {
    -1,
    (gchar *) "netid",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_params =
{
  {
    -1,
    (gchar *) "params",
    (gchar *) "a{ss}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_id,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_netid,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_params,
  NULL
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_OUT_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_OUT_ARG_status,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid =
{
  {
    -1,
    (gchar *) "ConnectSSID",
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid_OUT_ARG_pointers,
    NULL
  },
  "handle-connect-ssid",
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_ssid =
{
  {
    -1,
    (gchar *) "ssid",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_params =
{
  {
    -1,
    (gchar *) "params",
    (gchar *) "a{ss}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_id,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_ssid,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_params,
  NULL
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_OUT_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_OUT_ARG_status,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid =
{
  {
    -1,
    (gchar *) "ConnectHiddenSSID",
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid_OUT_ARG_pointers,
    NULL
  },
  "handle-connect-hidden-ssid",
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_IN_ARG_pin =
{
  {
    -1,
    (gchar *) "pin",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_IN_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_IN_ARG_id,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_IN_ARG_pin,
  NULL
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_OUT_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_OUT_ARG_status,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps =
{
  {
    -1,
    (gchar *) "ConnectWPS",
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps_OUT_ARG_pointers,
    NULL
  },
  "handle-connect-wps",
  FALSE
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_IN_ARG_id =
{
  {
    -1,
    (gchar *) "id",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_IN_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_IN_ARG_id,
  NULL
};

static const _ExtendedGDBusArgInfo _com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_OUT_ARG_status =
{
  {
    -1,
    (gchar *) "status",
    (gchar *) "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_OUT_ARG_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_OUT_ARG_status,
  NULL
};

static const _ExtendedGDBusMethodInfo _com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect =
{
  {
    -1,
    (gchar *) "CancelConnect",
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_IN_ARG_pointers,
    (GDBusArgInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect_OUT_ARG_pointers,
    NULL
  },
  "handle-cancel-connect",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _com_lgi_rdk_utils_wifimanagement1_method_info_pointers[] =
{
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssids,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_get_ssidparams,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_ssid,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_hidden_ssid,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_connect_wps,
  &_com_lgi_rdk_utils_wifimanagement1_method_info_cancel_connect,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _com_lgi_rdk_utils_wifimanagement1_interface_info =
{
  {
    -1,
    (gchar *) "com.lgi.rdk.utils.wifimanagement1",
    (GDBusMethodInfo **) &_com_lgi_rdk_utils_wifimanagement1_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "com-lgi-rdk-utils-wifimanagement1",
};


/**
 * com_lgi_rdk_utils_wifimanagement1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
com_lgi_rdk_utils_wifimanagement1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #ComLgiRdkUtilsWifimanagement1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
com_lgi_rdk_utils_wifimanagement1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * ComLgiRdkUtilsWifimanagement1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link>.
 */

/**
 * ComLgiRdkUtilsWifimanagement1Iface:
 * @parent_iface: The parent interface.
 * @handle_cancel_connect: Handler for the #ComLgiRdkUtilsWifimanagement1::handle-cancel-connect signal.
 * @handle_connect_hidden_ssid: Handler for the #ComLgiRdkUtilsWifimanagement1::handle-connect-hidden-ssid signal.
 * @handle_connect_ssid: Handler for the #ComLgiRdkUtilsWifimanagement1::handle-connect-ssid signal.
 * @handle_connect_wps: Handler for the #ComLgiRdkUtilsWifimanagement1::handle-connect-wps signal.
 * @handle_get_ssidparams: Handler for the #ComLgiRdkUtilsWifimanagement1::handle-get-ssidparams signal.
 * @handle_get_ssids: Handler for the #ComLgiRdkUtilsWifimanagement1::handle-get-ssids signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link>.
 */

typedef ComLgiRdkUtilsWifimanagement1Iface ComLgiRdkUtilsWifimanagement1Interface;
G_DEFINE_INTERFACE (ComLgiRdkUtilsWifimanagement1, com_lgi_rdk_utils_wifimanagement1, G_TYPE_OBJECT)

static void
com_lgi_rdk_utils_wifimanagement1_default_init (ComLgiRdkUtilsWifimanagement1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * ComLgiRdkUtilsWifimanagement1::handle-get-ssids:
   * @object: A #ComLgiRdkUtilsWifimanagement1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDs">GetSSIDs()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_lgi_rdk_utils_wifimanagement1_complete_get_ssids() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-ssids",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComLgiRdkUtilsWifimanagement1Iface, handle_get_ssids),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * ComLgiRdkUtilsWifimanagement1::handle-get-ssidparams:
   * @object: A #ComLgiRdkUtilsWifimanagement1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   * @arg_netid: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDParams">GetSSIDParams()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_lgi_rdk_utils_wifimanagement1_complete_get_ssidparams() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-ssidparams",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComLgiRdkUtilsWifimanagement1Iface, handle_get_ssidparams),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * ComLgiRdkUtilsWifimanagement1::handle-connect-ssid:
   * @object: A #ComLgiRdkUtilsWifimanagement1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   * @arg_netid: Argument passed by remote caller.
   * @arg_params: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectSSID">ConnectSSID()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_lgi_rdk_utils_wifimanagement1_complete_connect_ssid() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-connect-ssid",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComLgiRdkUtilsWifimanagement1Iface, handle_connect_ssid),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * ComLgiRdkUtilsWifimanagement1::handle-connect-hidden-ssid:
   * @object: A #ComLgiRdkUtilsWifimanagement1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   * @arg_ssid: Argument passed by remote caller.
   * @arg_params: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectHiddenSSID">ConnectHiddenSSID()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_lgi_rdk_utils_wifimanagement1_complete_connect_hidden_ssid() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-connect-hidden-ssid",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComLgiRdkUtilsWifimanagement1Iface, handle_connect_hidden_ssid),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    4,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * ComLgiRdkUtilsWifimanagement1::handle-connect-wps:
   * @object: A #ComLgiRdkUtilsWifimanagement1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   * @arg_pin: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectWPS">ConnectWPS()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_lgi_rdk_utils_wifimanagement1_complete_connect_wps() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-connect-wps",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComLgiRdkUtilsWifimanagement1Iface, handle_connect_wps),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING);

  /**
   * ComLgiRdkUtilsWifimanagement1::handle-cancel-connect:
   * @object: A #ComLgiRdkUtilsWifimanagement1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_id: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.CancelConnect">CancelConnect()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call com_lgi_rdk_utils_wifimanagement1_complete_cancel_connect() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-cancel-connect",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (ComLgiRdkUtilsWifimanagement1Iface, handle_cancel_connect),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_get_ssids:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDs">GetSSIDs()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_call_get_ssids_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_get_ssids_sync() for the synchronous, blocking version of this method.
 */
void
com_lgi_rdk_utils_wifimanagement1_call_get_ssids (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetSSIDs",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_get_ssids_finish:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @out_count: (out): Return location for return parameter or %NULL to ignore.
 * @out_netids: (out) (array zero-terminated=1): Return location for return parameter or %NULL to ignore.
 * @out_basic_params: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_call_get_ssids().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_call_get_ssids().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_get_ssids_finish (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    gint *out_status,
    guint *out_count,
    gchar ***out_netids,
    GVariant **out_basic_params,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(iu^as@aa{ss})",
                 out_status,
                 out_count,
                 out_netids,
                 out_basic_params);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_get_ssids_sync:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @out_count: (out): Return location for return parameter or %NULL to ignore.
 * @out_netids: (out) (array zero-terminated=1): Return location for return parameter or %NULL to ignore.
 * @out_basic_params: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDs">GetSSIDs()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_get_ssids() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_get_ssids_sync (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    gint *out_status,
    guint *out_count,
    gchar ***out_netids,
    GVariant **out_basic_params,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetSSIDs",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(iu^as@aa{ss})",
                 out_status,
                 out_count,
                 out_netids,
                 out_basic_params);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_netid: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDParams">GetSSIDParams()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams_sync() for the synchronous, blocking version of this method.
 */
void
com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_netid,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetSSIDParams",
    g_variant_new ("(ss)",
                   arg_id,
                   arg_netid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams_finish:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @out_count: (out): Return location for return parameter or %NULL to ignore.
 * @out_params: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams_finish (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    gint *out_status,
    guint *out_count,
    GVariant **out_params,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(iu@a{ss})",
                 out_status,
                 out_count,
                 out_params);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams_sync:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_netid: Argument to pass with the method invocation.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @out_count: (out): Return location for return parameter or %NULL to ignore.
 * @out_params: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDParams">GetSSIDParams()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_get_ssidparams_sync (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_netid,
    gint *out_status,
    guint *out_count,
    GVariant **out_params,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetSSIDParams",
    g_variant_new ("(ss)",
                   arg_id,
                   arg_netid),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(iu@a{ss})",
                 out_status,
                 out_count,
                 out_params);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_ssid:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_netid: Argument to pass with the method invocation.
 * @arg_params: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectSSID">ConnectSSID()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_call_connect_ssid_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_connect_ssid_sync() for the synchronous, blocking version of this method.
 */
void
com_lgi_rdk_utils_wifimanagement1_call_connect_ssid (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_netid,
    GVariant *arg_params,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ConnectSSID",
    g_variant_new ("(ss@a{ss})",
                   arg_id,
                   arg_netid,
                   arg_params),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_ssid_finish:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_call_connect_ssid().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_call_connect_ssid().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_connect_ssid_finish (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_ssid_sync:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_netid: Argument to pass with the method invocation.
 * @arg_params: Argument to pass with the method invocation.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectSSID">ConnectSSID()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_connect_ssid() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_connect_ssid_sync (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_netid,
    GVariant *arg_params,
    gint *out_status,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ConnectSSID",
    g_variant_new ("(ss@a{ss})",
                   arg_id,
                   arg_netid,
                   arg_params),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_ssid: Argument to pass with the method invocation.
 * @arg_params: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectHiddenSSID">ConnectHiddenSSID()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid_sync() for the synchronous, blocking version of this method.
 */
void
com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_ssid,
    GVariant *arg_params,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ConnectHiddenSSID",
    g_variant_new ("(ss@a{ss})",
                   arg_id,
                   arg_ssid,
                   arg_params),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid_finish:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid_finish (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid_sync:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_ssid: Argument to pass with the method invocation.
 * @arg_params: Argument to pass with the method invocation.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectHiddenSSID">ConnectHiddenSSID()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_connect_hidden_ssid_sync (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_ssid,
    GVariant *arg_params,
    gint *out_status,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ConnectHiddenSSID",
    g_variant_new ("(ss@a{ss})",
                   arg_id,
                   arg_ssid,
                   arg_params),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_wps:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_pin: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectWPS">ConnectWPS()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_call_connect_wps_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_connect_wps_sync() for the synchronous, blocking version of this method.
 */
void
com_lgi_rdk_utils_wifimanagement1_call_connect_wps (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_pin,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ConnectWPS",
    g_variant_new ("(ss)",
                   arg_id,
                   arg_pin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_wps_finish:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_call_connect_wps().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_call_connect_wps().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_connect_wps_finish (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_connect_wps_sync:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @arg_pin: Argument to pass with the method invocation.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectWPS">ConnectWPS()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_connect_wps() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_connect_wps_sync (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    const gchar *arg_pin,
    gint *out_status,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ConnectWPS",
    g_variant_new ("(ss)",
                   arg_id,
                   arg_pin),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_cancel_connect:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.CancelConnect">CancelConnect()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_call_cancel_connect_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_cancel_connect_sync() for the synchronous, blocking version of this method.
 */
void
com_lgi_rdk_utils_wifimanagement1_call_cancel_connect (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CancelConnect",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_cancel_connect_finish:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_call_cancel_connect().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_call_cancel_connect().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_cancel_connect_finish (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    gint *out_status,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_call_cancel_connect_sync:
 * @proxy: A #ComLgiRdkUtilsWifimanagement1Proxy.
 * @arg_id: Argument to pass with the method invocation.
 * @out_status: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.CancelConnect">CancelConnect()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_call_cancel_connect() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
com_lgi_rdk_utils_wifimanagement1_call_cancel_connect_sync (
    ComLgiRdkUtilsWifimanagement1 *proxy,
    const gchar *arg_id,
    gint *out_status,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CancelConnect",
    g_variant_new ("(s)",
                   arg_id),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(i)",
                 out_status);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_complete_get_ssids:
 * @object: A #ComLgiRdkUtilsWifimanagement1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 * @count: Parameter to return.
 * @netids: Parameter to return.
 * @basic_params: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDs">GetSSIDs()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_lgi_rdk_utils_wifimanagement1_complete_get_ssids (
    ComLgiRdkUtilsWifimanagement1 *object,
    GDBusMethodInvocation *invocation,
    gint status,
    guint count,
    const gchar *const *netids,
    GVariant *basic_params)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(iu^as@aa{ss})",
                   status,
                   count,
                   netids,
                   basic_params));
}

/**
 * com_lgi_rdk_utils_wifimanagement1_complete_get_ssidparams:
 * @object: A #ComLgiRdkUtilsWifimanagement1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 * @count: Parameter to return.
 * @params: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.GetSSIDParams">GetSSIDParams()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_lgi_rdk_utils_wifimanagement1_complete_get_ssidparams (
    ComLgiRdkUtilsWifimanagement1 *object,
    GDBusMethodInvocation *invocation,
    gint status,
    guint count,
    GVariant *params)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(iu@a{ss})",
                   status,
                   count,
                   params));
}

/**
 * com_lgi_rdk_utils_wifimanagement1_complete_connect_ssid:
 * @object: A #ComLgiRdkUtilsWifimanagement1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectSSID">ConnectSSID()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_lgi_rdk_utils_wifimanagement1_complete_connect_ssid (
    ComLgiRdkUtilsWifimanagement1 *object,
    GDBusMethodInvocation *invocation,
    gint status)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   status));
}

/**
 * com_lgi_rdk_utils_wifimanagement1_complete_connect_hidden_ssid:
 * @object: A #ComLgiRdkUtilsWifimanagement1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectHiddenSSID">ConnectHiddenSSID()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_lgi_rdk_utils_wifimanagement1_complete_connect_hidden_ssid (
    ComLgiRdkUtilsWifimanagement1 *object,
    GDBusMethodInvocation *invocation,
    gint status)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   status));
}

/**
 * com_lgi_rdk_utils_wifimanagement1_complete_connect_wps:
 * @object: A #ComLgiRdkUtilsWifimanagement1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.ConnectWPS">ConnectWPS()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_lgi_rdk_utils_wifimanagement1_complete_connect_wps (
    ComLgiRdkUtilsWifimanagement1 *object,
    GDBusMethodInvocation *invocation,
    gint status)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   status));
}

/**
 * com_lgi_rdk_utils_wifimanagement1_complete_cancel_connect:
 * @object: A #ComLgiRdkUtilsWifimanagement1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @status: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-lgi-rdk-utils-wifimanagement1.CancelConnect">CancelConnect()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
com_lgi_rdk_utils_wifimanagement1_complete_cancel_connect (
    ComLgiRdkUtilsWifimanagement1 *object,
    GDBusMethodInvocation *invocation,
    gint status)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(i)",
                   status));
}

/* ------------------------------------------------------------------------ */

/**
 * ComLgiRdkUtilsWifimanagement1Proxy:
 *
 * The #ComLgiRdkUtilsWifimanagement1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ComLgiRdkUtilsWifimanagement1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ComLgiRdkUtilsWifimanagement1Proxy.
 */

struct _ComLgiRdkUtilsWifimanagement1ProxyPrivate
{
  GData *qdata;
};

static void com_lgi_rdk_utils_wifimanagement1_proxy_iface_init (ComLgiRdkUtilsWifimanagement1Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (ComLgiRdkUtilsWifimanagement1Proxy, com_lgi_rdk_utils_wifimanagement1_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (ComLgiRdkUtilsWifimanagement1Proxy)
                         G_IMPLEMENT_INTERFACE (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1, com_lgi_rdk_utils_wifimanagement1_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (ComLgiRdkUtilsWifimanagement1Proxy, com_lgi_rdk_utils_wifimanagement1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1, com_lgi_rdk_utils_wifimanagement1_proxy_iface_init))

#endif
static void
com_lgi_rdk_utils_wifimanagement1_proxy_finalize (GObject *object)
{
  ComLgiRdkUtilsWifimanagement1Proxy *proxy = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (com_lgi_rdk_utils_wifimanagement1_proxy_parent_class)->finalize (object);
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  ComLgiRdkUtilsWifimanagement1Proxy *proxy = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_init (ComLgiRdkUtilsWifimanagement1Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = com_lgi_rdk_utils_wifimanagement1_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY, ComLgiRdkUtilsWifimanagement1ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), com_lgi_rdk_utils_wifimanagement1_interface_info ());
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_class_init (ComLgiRdkUtilsWifimanagement1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = com_lgi_rdk_utils_wifimanagement1_proxy_finalize;
  gobject_class->get_property = com_lgi_rdk_utils_wifimanagement1_proxy_get_property;
  gobject_class->set_property = com_lgi_rdk_utils_wifimanagement1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = com_lgi_rdk_utils_wifimanagement1_proxy_g_signal;
  proxy_class->g_properties_changed = com_lgi_rdk_utils_wifimanagement1_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (ComLgiRdkUtilsWifimanagement1ProxyPrivate));
#endif
}

static void
com_lgi_rdk_utils_wifimanagement1_proxy_iface_init (ComLgiRdkUtilsWifimanagement1Iface *iface)
{
}

/**
 * com_lgi_rdk_utils_wifimanagement1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_proxy_new_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
com_lgi_rdk_utils_wifimanagement1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.lgi.rdk.utils.wifimanagement1", NULL);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_proxy_new().
 *
 * Returns: (transfer full) (type ComLgiRdkUtilsWifimanagement1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ComLgiRdkUtilsWifimanagement1 *
com_lgi_rdk_utils_wifimanagement1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return COM_LGI_RDK_UTILS_WIFIMANAGEMENT1 (ret);
  else
    return NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ComLgiRdkUtilsWifimanagement1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ComLgiRdkUtilsWifimanagement1 *
com_lgi_rdk_utils_wifimanagement1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.lgi.rdk.utils.wifimanagement1", NULL);
  if (ret != NULL)
    return COM_LGI_RDK_UTILS_WIFIMANAGEMENT1 (ret);
  else
    return NULL;
}


/**
 * com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like com_lgi_rdk_utils_wifimanagement1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.lgi.rdk.utils.wifimanagement1", NULL);
}

/**
 * com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type ComLgiRdkUtilsWifimanagement1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ComLgiRdkUtilsWifimanagement1 *
com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return COM_LGI_RDK_UTILS_WIFIMANAGEMENT1 (ret);
  else
    return NULL;
}

/**
 * com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like com_lgi_rdk_utils_wifimanagement1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type ComLgiRdkUtilsWifimanagement1Proxy): The constructed proxy object or %NULL if @error is set.
 */
ComLgiRdkUtilsWifimanagement1 *
com_lgi_rdk_utils_wifimanagement1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.lgi.rdk.utils.wifimanagement1", NULL);
  if (ret != NULL)
    return COM_LGI_RDK_UTILS_WIFIMANAGEMENT1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * ComLgiRdkUtilsWifimanagement1Skeleton:
 *
 * The #ComLgiRdkUtilsWifimanagement1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * ComLgiRdkUtilsWifimanagement1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #ComLgiRdkUtilsWifimanagement1Skeleton.
 */

struct _ComLgiRdkUtilsWifimanagement1SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_com_lgi_rdk_utils_wifimanagement1_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  ComLgiRdkUtilsWifimanagement1Skeleton *skeleton = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_com_lgi_rdk_utils_wifimanagement1_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  ComLgiRdkUtilsWifimanagement1Skeleton *skeleton = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_com_lgi_rdk_utils_wifimanagement1_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  ComLgiRdkUtilsWifimanagement1Skeleton *skeleton = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _com_lgi_rdk_utils_wifimanagement1_skeleton_vtable =
{
  _com_lgi_rdk_utils_wifimanagement1_skeleton_handle_method_call,
  _com_lgi_rdk_utils_wifimanagement1_skeleton_handle_get_property,
  _com_lgi_rdk_utils_wifimanagement1_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return com_lgi_rdk_utils_wifimanagement1_interface_info ();
}

static GDBusInterfaceVTable *
com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_com_lgi_rdk_utils_wifimanagement1_skeleton_vtable;
}

static GVariant *
com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  ComLgiRdkUtilsWifimanagement1Skeleton *skeleton = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _com_lgi_rdk_utils_wifimanagement1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _com_lgi_rdk_utils_wifimanagement1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.lgi.rdk.utils.wifimanagement1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void com_lgi_rdk_utils_wifimanagement1_skeleton_iface_init (ComLgiRdkUtilsWifimanagement1Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (ComLgiRdkUtilsWifimanagement1Skeleton, com_lgi_rdk_utils_wifimanagement1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (ComLgiRdkUtilsWifimanagement1Skeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1, com_lgi_rdk_utils_wifimanagement1_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (ComLgiRdkUtilsWifimanagement1Skeleton, com_lgi_rdk_utils_wifimanagement1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1, com_lgi_rdk_utils_wifimanagement1_skeleton_iface_init))

#endif
static void
com_lgi_rdk_utils_wifimanagement1_skeleton_finalize (GObject *object)
{
  ComLgiRdkUtilsWifimanagement1Skeleton *skeleton = COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (com_lgi_rdk_utils_wifimanagement1_skeleton_parent_class)->finalize (object);
}

static void
com_lgi_rdk_utils_wifimanagement1_skeleton_init (ComLgiRdkUtilsWifimanagement1Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = com_lgi_rdk_utils_wifimanagement1_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON, ComLgiRdkUtilsWifimanagement1SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
com_lgi_rdk_utils_wifimanagement1_skeleton_class_init (ComLgiRdkUtilsWifimanagement1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = com_lgi_rdk_utils_wifimanagement1_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = com_lgi_rdk_utils_wifimanagement1_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (ComLgiRdkUtilsWifimanagement1SkeletonPrivate));
#endif
}

static void
com_lgi_rdk_utils_wifimanagement1_skeleton_iface_init (ComLgiRdkUtilsWifimanagement1Iface *iface)
{
}

/**
 * com_lgi_rdk_utils_wifimanagement1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-lgi-rdk-utils-wifimanagement1.top_of_page">com.lgi.rdk.utils.wifimanagement1</link>.
 *
 * Returns: (transfer full) (type ComLgiRdkUtilsWifimanagement1Skeleton): The skeleton object.
 */
ComLgiRdkUtilsWifimanagement1 *
com_lgi_rdk_utils_wifimanagement1_skeleton_new (void)
{
  return COM_LGI_RDK_UTILS_WIFIMANAGEMENT1 (g_object_new (TYPE_COM_LGI_RDK_UTILS_WIFIMANAGEMENT1_SKELETON, NULL));
}

